import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Frontend Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body  cz-shortcut-listen="true">
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
